name:                fizzbuzz
version:             0.1.0.0
license:             BSD3
author:              "Eli Kogan-Wang"
copyright:           "2021 Eli Kogan-Wang"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

executables:
  fizzbuzz:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2